services:
  - type: web
    name: lee-editor
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: VITE_BASE44_APP_ID
        sync: false
      - key: VITE_BASE44_APP_BASE_URL
        sync: false
      - key: VITE_GOOGLE_CLIENT_ID
        sync: false
